### ISSUE TITLE
Initial install fails with Talos 1.10.1

### ISSUE THREAD

**Issue by nbraud** [pulumiverse/pulumi-talos#158]
I am trying to bring up a Talos cluster on bare metal, and installing via `talos.machine.ConfigurationApply` seems to be broken: after fetching the installer's image, the installer's CLI usage message is printed out, and an install error is reported.

Here is the Pulumi/Python code I used in the attempt(s) :
```py
from pathlib import Path
import yaml

import pulumi as pu
import pulumiverse_talos as talos


version = pu.Config().require("talosVersion")
secrets = talos.machine.Secrets(
    "talos-secrets",
    talos_version = version,
)

rkube1_addr = "192.168.32.81"
rkube1_cfg = talos.machine.get_configuration_output(
    cluster_name = "rkube",
    talos_version = version,
    machine_type = "controlplane",
    cluster_endpoint = "https://192.168.32.80:6443",
    machine_secrets = secrets.machine_secrets.apply(lambda ms: {  # HACK for pulumiverse/pulumi-talos#103
        "certs": {
            "k8sAggregator": ms.certs.k8s_aggregator,
            "os": ms.certs.os,
            "etcd": ms.certs.etcd,
            "k8s": ms.certs.k8s,
            "k8sServiceaccount": ms.certs.k8s_serviceaccount,
        },
        "secrets": {
            "bootstrapToken": ms.secrets.bootstrap_token,
            "secretboxEncryptionSecret": ms.secrets.secretbox_encryption_secret,
        },
        "trustdinfo": ms.trustdinfo,
        "cluster": {
            "id": ms.cluster.id,
            "secret": ms.cluster.secret,
        },
    }),
    config_patches = [
        (Path.cwd() / "rkube1.yaml").read_text(),
    ],
)

rkube1_install = talos.machine.ConfigurationApply(
    "rkube1-install",
    client_configuration = secrets.client_configuration,
    machine_configuration_input = rkube1_cfg.machine_configuration,
    node = rkube1_addr,
)
```
```yaml
# rkube1.yaml
machine:
  install:
    disk: /dev/nvme0n1

  network:
    hostname: rkube1
    interfaces:
      - interface: enp1s0
        dhcp: false
        vlans:
          - vlanId: 32
            vip:
              ip: 192.168.32.80
            dhcp: false
            addresses:
              - 192.168.32.81/24
            routes:
              - network: 0.0.0.0/0
                gateway: 192.168.32.254
    nameservers:
      - 192.168.32.254
      - 9.9.9.9
      - 149.112.112.112  # quad9 fallback address
```
